export const PAPERS = [
  {
    title: 'Artificial Intelligence',
    list: [
      'Intelligent multi-Agent Systems',
      'Planning and Decision Support Systems',
      'Big Data Analytics',
      'Case-based Reasoning',
      'Evolutionary Computing',
      'Information Retrieval ',
      'Soft Computing ',
      'Machine Learning and Deep Learning ',
      'Computer vision',
      'Natural Language Processing, Speech and Text processing',
      'Robotics',
      'Social Network Analysis ',
      'AI and Cyber security',
      'Cognitive Science',
      'AI and its applications',
    ],
  },
  {
    title: 'Knowledge Engineering',
    list: [
      'Knowledge representation and reasoning',
      'Knowledge acquisition',
      'Temporal knowledge',
      'Uncertainty in knowledge',
      'Knowledge-driven learning',
      'Knowledge fusion for decision making ',
      'Integration of machine learning and knowledge representation ',
      'Knowledge extraction from texts/videos, big data/Web ',
      'Knowledge discovery from very large databases',
      'Semantic database systems',
      'Knowledge for Cognitive analytics ',
      'Knowledge for robotics',
      'Knowledge-based software engineering',
      'Knowledge-based systems in life sciences',
      'Semantic Web: Content and ontological engineering',
      'Reasoning on Knowledge Graph',
      'Machine Learning on Knowledge Graph',
      'Explainable AI techniques using Knowledge Graph',
      'Knowledge Graph application and platform using reasoning, Machine Learning and Explainable AI techniques',
    ],
  },
  {
    title: 'IoT Technologies and applications',
    list: [
      '5G/6G Networks and IoT',
      'IoT Interoperability and Multi-Platform Integration',
      'IoT architecture, protocols and Standards',
      'Wireless Sensor Network for IoT',
      'Software Defined Network',
      'Sensors Data Management, IoT Mining and Analytics',
      'Big Data and Information Integrity in IoT',
      'IoT Security and Trust ',
      'Communication Security in IoT',
      'Heterogeneous Networks, Web of Things, Web of Everything',
      'Internet of Nano Things',
      'Industrial IoT and Factory of Things ',
      'Green IoT',
      'IoT and block chain',
      'IoT applications for smart systems',
    ],
  },
];
